apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-shop-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-shop-2
  template:
    metadata:
      labels:
        app: simple-shop-2
    spec:
      containers:
        - name: simple-shop-2
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
